# Generated by Django 5.2.1 on 2025-05-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='The 15th of each month.', unique=True, verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='The 14th of each month.', unique=True, verbose_name='End Date')),
                ('dolar_peso_rate', models.IntegerField(default=4500, help_text='The rate of the dollar to peso for this month.', verbose_name='Dolar to Peso rate')),
                ('pay_rate_min', models.IntegerField(default=0.18, help_text='The pay per minute for this month.', verbose_name='Pay rate')),
                ('is_current', models.BooleanField(default=False, help_text='Is this the current month?', verbose_name='Is current month?')),
            ],
        ),
    ]
