# Generated by Django 5.2.1 on 2025-05-26 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start', models.DateTimeField(help_text='The time the current call started.', verbose_name='Call started at')),
                ('day_end', models.DateTimeField(help_text='The time the current call ended.', verbose_name='Call ended at')),
                ('active', models.BooleanField(default=False, help_text='Is this day active?', verbose_name='Is_active?')),
                ('work_month', models.ForeignKey(help_text='The month this work day belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='budget.workmonth', verbose_name='Work month')),
            ],
        ),
    ]
