# Generated by Django 5.2.1 on 2025-05-26 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_workday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_start', models.DateTimeField(help_text='The time the current call started.', verbose_name='Call started at')),
                ('call_end', models.DateTimeField(blank=True, default=None, help_text='The time the current call ended.', null=True, verbose_name='Call ended at')),
                ('active', models.BooleanField(default=False, help_text='Is this call active?', verbose_name='Is active?')),
                ('note', models.CharField(blank=True, default='', help_text='A note for this call.', max_length=255, verbose_name='Note')),
                ('work_day', models.ForeignKey(help_text='The work day this call belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='budget.workday', verbose_name='Work day')),
            ],
        ),
    ]
