# Generated by Django 5.2.1 on 2025-05-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmonth',
            name='end_date',
            field=models.DateTimeField(help_text='The 14th of each month.', unique=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='workmonth',
            name='start_date',
            field=models.DateTimeField(help_text='The 15th of each month.', unique=True, verbose_name='Start Date'),
        ),
    ]
