# Generated by Django 5.2.1 on 2025-05-26 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_workmonth_end_date_alter_workmonth_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='day_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 23, 59, 59, 577397, tzinfo=datetime.timezone.utc), help_text='The time the work day ended.', verbose_name='Call ended at'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='day_start',
            field=models.DateTimeField(auto_now_add=True, help_text='The time the current work day started.', verbose_name='Call started at'),
        ),
    ]
