# Generated by Django 5.2.1 on 2025-05-26 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_workday_day_end_alter_workday_day_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_start',
            field=models.DateTimeField(auto_now_add=True, help_text='The time the current call started.', verbose_name='Call started at'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='day_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 23, 59, 59, 144551, tzinfo=datetime.timezone.utc), help_text='The time the work day ended.', verbose_name='Call ended at'),
        ),
    ]
