# Generated by Django 5.2.1 on 2025-05-26 19:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_workday_interpreter_alter_workday_day_end'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workmonth',
            name='interpreter',
            field=models.ForeignKey(default=None, help_text='The interpreter who worked this month.', on_delete=django.db.models.deletion.CASCADE, related_name='work_months', to=settings.AUTH_USER_MODEL, verbose_name='Interpreter'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='day_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 23, 59, 59, 358428, tzinfo=datetime.timezone.utc), help_text='The time the work day ended.', verbose_name='Call ended at'),
        ),
    ]
