# Generated by Django 5.2.1 on 2025-06-02 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_alter_workday_day_end_alter_workday_interpreter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 2, 0, 29, 1, 949096, tzinfo=datetime.timezone.utc), help_text='The time the current call ended.', null=True, verbose_name='Call ended at'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='day_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 23, 59, 59, 948291, tzinfo=datetime.timezone.utc), help_text='The time the work day ended.', verbose_name='Call ended at'),
        ),
    ]
