# Generated by Django 5.2.1 on 2025-06-14 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_alter_call_call_end_alter_workday_day_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 15, 0, 12, 15, 673114, tzinfo=datetime.timezone.utc), help_text='The time the current call ended.', null=True, verbose_name='Call ended at'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='day_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 4, 59, 59, 672799, tzinfo=datetime.timezone.utc), help_text='The time the work day ended.', verbose_name='Call ended at'),
        ),
    ]
