# Generated by Django 5.1.7 on 2025-03-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpreter',
            name='email',
            field=models.EmailField(blank=True, max_length=150, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='interpreter',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='username'),
        ),
    ]
