# Generated by Django 2.2.12 on 2025-01-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpreter',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
