# Generated by Django 2.2.12 on 2025-02-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='abbreviation',
            field=models.ManyToManyField(blank=True, null=True, to='main.Abbreviation'),
        ),
    ]
