# Generated by Django 2.2.12 on 2025-02-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250218_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='abbreviation',
            field=models.ManyToManyField(blank=True, to='main.Abbreviation'),
        ),
    ]
