# Generated by Django 5.1.7 on 2025-03-09 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Definition')),
                ('abbreviation', models.ManyToManyField(blank=True, to='main.abbreviation')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
                ('english', models.ManyToManyField(to='main.english')),
                ('spanish', models.ManyToManyField(to='main.spanish')),
            ],
        ),
    ]
